# Site settings
title: Rafael Wiska-Ilnicki
description: Second-Year Software Engineering Student at the University of Guelph
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://rafaelwi.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rafael Wiska-Ilnicki
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Second-Year Software Engineering Student at the University of Guelph
email: rafwiskailnicki@gmail.com
#twitter_username: lorem_ipsum
github_username:  rafaelwi
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
