# Site settings
title: Rafael's Portfolio
description: Second-Year Software Engineering Student
url: "https://rafaelwi.github.io"

# User settings
username: Rafael Wiska-Ilnicki
user_description: "Hi, I'm Rafael, a Second-Year Software Engineering Student
with a Business Minor at the University of Guelph. I live in the 
Kitchener-Waterloo area. I have been interested in technology and programming
for a long time. In my free time, I like to work on my personal projects (which
you can find below), as well as reading and biking.
<br><br>
I hope you enjoy my website and portfolio!" 
user_title: "Second-Year Software Engineering Student"
email: rafwiskailnicki@gmail.com
github_username:  rafaelwi

exclude: ['package.json', 'src' , 'node_modules']
