# Site settings
title: Rafael Wiska-Ilnicki
description: Second-Year Software Engineering Student
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://rafaelwi.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rafael Wiska-Ilnicki
user_description: "Hi, I'm Rafael, a Second-Year Software Engineering Student
with a Business Minor at the University of Guelph. I live in the 
Kitchener-Waterloo area. I've been interested in programming ever since I first
played video games such as <i>Super Mario 64</i> and <i>Hey You Pikachu</i>. 
I'm a natural-born tinkerer who loves a good challenge, and I enjoy working in 
groups. 
<br><br>
I hope you enjoy my website and portfolio!" 
user_title: "Second-Year Software Engineering Student at the University of 
Guelph"
email: rafwiskailnicki@gmail.com
#twitter_username: lorem_ipsum
github_username:  rafaelwi
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
